# Environment file for GRiMP Notebooks
name: greenlandMapping
#
channels:
  - conda-forge
dependencies:
  - python=3.9
  # Pin this to avoid gdal issues on osx
  - blosc<=1.21.0
  - dask
  - datashader
  - fsspec
  - gdal=3.4.2
  - tiledb=2.7.1
  - geoviews  
  - geopandas
  - holoviews
  - hvplot
  - jupyter-panel-proxy
  - jupyterlab>=3
  - nbgitpuller
  - panel
  - param
  - pip
  - progressbar2
  - qgis
  - rasterio
  - rioxarray
  - stackstac
  - pip:
    - git+https://github.com/fastice/grimpfunc.git@master
    - git+https://github.com/fastice/grimpqgis.git@master
    - git+https://github.com/fastice/nisardev.git@main
    - git+https://github.com/developmentseed/rio-stac@main
    
    
